server:
  port: 18087

spring:
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719

  sleuth:
    sampler:
      probability: 1

  redis:
    host: 192.168.153.188

feign:
  sentinel:
    enabled: true
