server:
  port: 18088

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: 127.0.0.1:8080

  sleuth:
    sampler:
      probability: 1

  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false

feign:
  sentinel:
    enabled: true

thread:
  pool:
    coreSize: 100
    maxSize: 500
    aliveTime: 5
    blockingQueueSize: 1000