#nacos
#sentinel dashboard port
#seluth sample
#redis
#datasource
#feign
#mybatis-plus

server:
  port: 18085

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        #与dashboard连接的端口号，被占用就递增
        port: 8719

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_sms
    username: root
    password: root

  #zipkin链路追踪配置
  zipkin:
    base-url: http://localhost:9411
    #链路追踪方式: web rabbit activemq kafka
    sender:
      type: web
    #不追踪zipkin自己的请求
    discovery-client-enabled: false
  #采样率 100%
  sleuth:
    sampler:
      probability: 1

#redis配置
  redis:
    host: 192.168.153.188

feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  #可省略包名别名扫描，mapper中resultType或resultMap使用entity对象时
  type-aliases-package: cn.link.inkmall.sms.entity
  global-config:
    db-config:
      id-type: auto